services:
  - type: web
    name: educloud-elearn
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn elearn_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
